build:
  version: "2.0"

card:
  message: "Welcome to Bank card QA APIs "
  contactDetails:
    name: "Vitorino OwO - Developer"
    email: "vitorino@bank.com"
  onCallSupport:
    - (666) 555-1234
    - (666) 523-1345