spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loan:
  message: "Welcome to Bank loan QA APIs "
  contactDetails:
    name: "Bogas - Developer"
    email: "bogas@bank.com"
  onCallSupport:
    - (666) 555-1234
    - (666) 523-1345