spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to Bank accounts Proud APIs "
  contactDetails:
    name: "Pedro - Product Owner"
    email: "pedro@bank.com"
  onCallSupport:
    - (777) 555-1234
    - (777) 523-1345